CREATE DATABASE OFICINA_ADRYAN;
USE OFICINA_ADRYAN;

-- CRIAR TABELAS 
CREATE TABLE CLIENTES (
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY ,
NOME VARCHAR (50) NOT NULL,
CPF VARCHAR (14) NOT NULL,
DATA_ENTREGUE DATETIME  (10),
NUMERO_CNH CHAR (9),
VEICULO_CLIENTE VARCHAR (30)
);

CREATE TABLE PAGAMENTOS (
ID_PAGAMENTOS INT AUTO_INCREMENT PRIMARY KEY,
DINHEIRO INT (6) NOT NULL,
CARNÊ INT (6) NOT NULL
);