-- Active: 1788351836192@@127.0.0.1@3306@castello_relacionamentos

CREATE DATABASE IF NOT EXISTS CASTELLO_RELACIONAMENTOS;
USE CASTELLO_RELACIONAMENTOS;

CREATE TABLE CLIENTES(
    ID_CLIENTES INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CLIENTE VARCHAR(100) NOT NULL
);

CREATE TABLE PEDIDOS (
    ID_PEDIDOS INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    DATA_PEDIDO DATE NOT NULL,
    VALOR_TOTAL DECIMAL (10,2) NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTES)
);

CREATE TABLE ESTOQUE(
    ID_ESTOQUE INT AUTO_INCREMENT PRIMARY KEY,
    ID_PRODUTO INT NOT NULL UNIQUE,
    QUANTIDADE INT NOT NULL,
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS (ID_PRODUTO)

);

CREATE TABLE PRODUTOS (
    ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PRODUTO VARCHAR (100) NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL
);

SELECT * FROM ESTOQUE;


INSERT INTO produtos (NOME_PRODUTO, PRECO) VALUES
('PRODUTO A', 10.00),
('PRODUTO B', 20.00),
('PRODUTO C', 30.00);

-- DESAFIOS  CARDINALIDADES

-- QUESTÃO 1

-- CATEGORIA(1,n)  <POSSUI>  (1,1) PRODUTOS

-- -- QUESTÃO 2 
-- FUNCIONARIO(1,1)  <REGISTRA> (1,N) PEDIDO

-- -- QUESTÃO 3
-- FORNECEDOR (1,N) <COMERCIALIZA> (1,N) PRODUTOS

-- -- QUESTÃO 4
-- CLIENTE(1,1) <RESERVA> (0,N) MESA

-- -- QUESTÃO 5
-- PEDIDO (1,N) <POSSUI> (1,N) ITENS 
