-- PROJETO SMART COFFEE

CREATE DATABASE SMARTCOFFEE_ADRYAN; 
CREATE  DATABASE IF NOT EXISTS SMARTCOFFEE_ADRYAN;


CREATE TABLE CLIENTES(
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
CPF VARCHAR (14) NOT NULL UNIQUE,
NOME VARCHAR(60) NOT NULL,
TELEFONE VARCHAR (15) NOT NULL,
ENDERECO VARCHAR (100),
DATA_NASCIMENTO DATE NOT NULL,
STATUS_CLIENTES ENUM ('PENDENTE', 'ATIVO', 'INATIVO') DEFAULT "ATIVO",
DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PEDIDOS(
ID_PEDIDOS INT PRIMARY KEY




);

CREATE TABLE PRODUTO (
    ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_DO_PRODUTO VARCHAR(100) NOT NULL,
    QUANTIDADE INT DEFAULT 0,
    TIPO VARCHAR(50),
    PRECO DECIMAL(10, 2) NOT NULL,
    VALIDADE DATE
);

CREATE TABLE PAGAMENTOS (
    ID_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY,
    PRECO DECIMAL(10, 2) NOT NULL,
    METODOS_DE_PAGAMENTO ENUM('Pix', 'Cartao', 'Dinheiro') DEFAULT 'Pix',
    CLIENTE VARCHAR(100),
    DATA_DE_ENTREGA DATE,
    HORARIO_DA_ENTREGA TIME
);

CREATE TABLE ESTOQUE (
    ID_ESTOQUE INT AUTO_INCREMENT PRIMARY KEY,
    QUANTIDADE INT NOT NULL,
    ULTIMA_LOCALIZACAO VARCHAR(100),
    LOCALIZACAO VARCHAR(100),
    ESTOQUE_MINIMO INT DEFAULT 0
);

USE SMARTCOFFEE_ADRYAN;