-- COMANDO PARA CRIAR BD -- 
-- 1 
 CREATE DATABASE ACADEMIA_ADRYAN;
CREATE DATABASE IF NOT EXISTS ACADEMIA_ADRYAN;

-- 2 
-- ATUALIZAR SCHEMAS 

-- COMANDO PARA ATIVAR BD
USE ACADEMIA_ADRYAN ;

-- COMANDO PARA APAGAR BD--
DROP DATABASE ACADEMIA_ADRYAN;

-- COMANDO CRIAR TABELA --
CREATE TABLE IF NOT EXISTS CLIENTES ( 
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
CPF VARCHAR (14) NOT NULL UNIQUE,
NOME VARCHAR(60) NOT NULL,
TELEFONE VARCHAR (15) NOT NULL,
ENDERECO VARCHAR (100),
DATA_NASCIMENTO DATE NOT NULL,
STATUS_CLIENTES ENUM ('PENDENTE', 'ATIVO', 'INATIVO') DEFAULT "ATIVO",
DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);
 CREATE TABLE PLANO (
 ID_PLANO INT AUTO_INCREMENT PRIMARY KEY,
 NOME_PLANO VARCHAR (20) NOT NULL ,
 TIPOS_PLANO CHAR(10) DEFAULT "MENSAL",
 VALOR DECIMAL (5,2) DEFAULT 0.00,   
 ADICIONAIS CHAR (10) DEFAULT "EXAME",
 OBSERVAÇÃO TEXT,
 DURACAO_PLANO INT NOT NULL
 );


-- MODIFICAR TIPO DE DADOS OU CAMPOS
ALTER TABLE CLIENTESS MODIFY EMAIL VARCHAR (150);

-- RENOMEAR TABELAS
RENAME TABLE CLIENTES TO CLIENTESS;

-- EXCLUIR ATRIBUTO 
ALTER TABLE CLIENTESS DROP COLUMN EMAIL;
 
-- COMANDOS PARA ALTERAR E CORRIGIR
-- ADICIONANDO UM CAMPO (ATRIBUTO) NOVO
ALTER TABLE CLIENTESS ADD EMAIL VARCHAR(100);


-- VISUALIZAR TABELAS
SHOW TABLES ;

-- LIMPAR DADOS DA TABELA
TRUNCATE TABLE CLIENTES;

-- INSERIR DADOS NO BCD
INSERT INTO CLIENTES (ID_CLIENTES, NOME, CPF, TELEFONE, ENDERECO, DATA_NASCIMENTO, STATUS_CLIENTE, DATA_CADASTRO)
VALUES ('', 'ADRYAN', '609.976.818-10', '(19) 98454,3266', 'R. ANNA DELFINA DA SILVA', '31/08/2009', 'ATIVO', '');

INSERT INTO FUNCIONARIOS (ID_FUNCIONARIO, EMAIL)
 VALUES (1, 'ADRYAN.GALZERANO@EDU.SENAI.BR');
 
 -- COMANDO PARA CONSULTAR INFORMACOES 
 SELECT * FROM FUNCIONARIOS; 
 
 CREATE TABLE FUNCIONARIOS (
 ID_FUNCIONARIO INT PRIMARY KEY,
 EMAIL VARCHAR (255) UNIQUE
 );
 
 