-- COMENTÁRIOS
-- COMANDO PARA CRIAR BANCO DE DADOS
CREATE DATABASE GYM;

-- APAGAR BANCO DE DADOS 
DROP DATABASE GYM;

-- APAGAR TABELAS DO BANCO
DROP TABLE GYM;

-- ATIVAR BANCO DE DADOS
USE GYM;

-- CRIAR TABELAS
CREATE TABLE CLIENTES (
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY, -- CHAVE PRIMARIA NOS ID´s
NOME VARCHAR (60) NOT NULL,
CPF VARCHAR(14) NOT NULL UNIQUE,-- OBRIGATORIO
ENDERECO VARCHAR (60) NOT NULL,  -- OBRIGATORIO
EMAIL VARCHAR (100) NOT NULL,
TELEFONE VARCHAR (100) NOT NULL
);
